name: Build Ghidra ESP32 Flash Loader

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Clone Ghidra release
      run: |
        wget https://github.com/NationalSecurityAgency/ghidra/releases/download/Ghidra_11.1.2_build/ghidra_11.1.2_PUBLIC_20240709.zip
        unzip ghidra_11.1.2_PUBLIC_20240709.zip -d /opt/
        export GHIDRA_INSTALL_DIR=/opt/ghidra_11.1.2_PUBLIC

    - name: Setup Gradle 8.1.0
      uses: gradle/actions/setup-gradle@v4
      with:
        gradle-version: "8.10"
      
    - name: Build with Gradle 8.10
      run: |
        export GHIDRA_INSTALL_DIR=/opt/ghidra_11.1.2_PUBLIC
        gradle
        
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ghidra-esp32-flash-loader
        path: /home/runner/work/ghidra-esp32-flash-loader/ghidra-esp32-flash-loader/dist
