name: Build Ghidra ESP32 Flash Loader

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y wget openjdk-11-jdk gradle

    - name: Clone Ghidra release
      run: |
        wget https://github.com/NationalSecurityAgency/ghidra/releases/download/Ghidra_11.1.2_build/ghidra_11.1.2_PUBLIC_20240709.zip
        unzip ghidra_11.1.2_PUBLIC_20240709.zip -d /opt/
        export GHIDRA_INSTALL_DIR=/opt/ghidra_11.1.2_PUBLIC

    - name: Set up Gradle
      uses: gradle/gradle-build-action@v2
      with:
        arguments: assemble

    - name: Build project with Gradle
      run: |
        export GHIDRA_INSTALL_DIR=/opt/ghidra_11.1.2_PUBLIC
        gradle build
